basepath = ".."
locales = [
    "ach",
    "af",
    "an",
    "ar",
    "ast",
    "az",
    "be",
    "bg",
    "bn",
    "bo",
    "br",
    "brx",
    "bs",
    "ca",
    "ca-valencia",
    "cak",
    "ckb",
    "cs",
    "cy",
    "da",
    "de",
    "dsb",
    "el",
    "en-CA",
    "en-GB",
    "eo",
    "es-AR",
    "es-CL",
    "es-ES",
    "es-MX",
    "et",
    "eu",
    "fa",
    "ff",
    "fi",
    "fr",
    "fur",
    "fy-NL",
    "ga-IE",
    "gd",
    "gl",
    "gn",
    "gu-IN",
    "he",
    "hi-IN",
    "hr",
    "hsb",
    "hu",
    "hy-AM",
    "hye",
    "ia",
    "id",
    "is",
    "it",
    "ja",
    "ja-JP-mac",
    "ka",
    "kab",
    "kk",
    "km",
    "kn",
    "ko",
    "lij",
    "lo",
    "lt",
    "ltg",
    "lv",
    "meh",
    "mk",
    "ml",
    "mr",
    "ms",
    "my",
    "nb-NO",
    "ne-NP",
    "nl",
    "nn-NO",
    "oc",
    "pa-IN",
    "pl",
    "pt-BR",
    "pt-PT",
    "rm",
    "ro",
    "ru",
    "sat",
    "sc",
    "scn",
    "sco",
    "si",
    "sk",
    "skr",
    "sl",
    "son",
    "sq",
    "sr",
    "sv-SE",
    "szl",
    "ta",
    "te",
    "tg",
    "th",
    "tl",
    "tr",
    "trs",
    "uk",
    "ur",
    "uz",
    "vi",
    "wo",
    "xh",
    "zh-CN",
    "zh-TW",
]
includes = [
    { path = "_configs/toolkit.toml" },
    { path = "_configs/devtools-client.toml" },
]

[env]
l = "{l10n_base}/{locale}/"

[[paths]]
reference = "browser/**"
l10n = "{l}browser/**"

[[paths]]
reference = "browser/branding/official/**"
l10n = "{l}browser/branding/official/**"

[[paths]]
reference = "browser/extensions/formautofill/**"
l10n = "{l}browser/extensions/formautofill/**"

[[paths]]
reference = "browser/extensions/report-site-issue/**"
l10n = "{l}browser/extensions/report-site-issue/**"

[[paths]]
reference = "devtools/startup/**"
l10n = "{l}devtools/startup/**"

[[filters]]
path = [
    "{l}browser/firefox-l10n.js",
]
action = "ignore"
