# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

basepath = ".."

locales = [
    "ach",
    "an",
    "ar",
    "as",
    "ast",
    "az",
    "be",
    "bg",
    "bn-BD",
    "bn-IN",
    "br",
    "bs",
    "ca",
    "cak",
    "cs",
    "cy",
    "da",
    "de",
    "dsb",
    "el",
    "en-CA",
    "en-GB",
    "en-ZA",
    "eo",
    "es-AR",
    "es-CL",
    "es-ES",
    "es-MX",
    "et",
    "eu",
    "fa",
    "ff",
    "fi",
    "fr",
    "fy-NL",
    "ga-IE",
    "gd",
    "gl",
    "gn",
    "gu-IN",
    "he",
    "hi-IN",
    "hr",
    "hsb",
    "hu",
    "hy-AM",
    "ia",
    "id",
    "is",
    "it",
    "ja",
    "ka",
    "kab",
    "kk",
    "km",
    "kn",
    "ko",
    "lij",
    "lo",
    "lt",
    "ltg",
    "lv",
    "mai",
    "meh",
    "mix",
    "ml",
    "mr",
    "ms",
    "my",
    "nb-NO",
    "ne-NP",
    "nl",
    "nn-NO",
    "oc",
    "or",
    "pa-IN",
    "pl",
    "pt-BR",
    "pt-PT",
    "rm",
    "ro",
    "ru",
    "sk",
    "sl",
    "son",
    "sq",
    "sr",
    "sv-SE",
    "ta",
    "te",
    "th",
    "tl",
    "tr",
    "trs",
    "uk",
    "ur",
    "uz",
    "vi",
    "wo",
    "xh",
    "zam",
    "zh-CN",
    "zh-TW",
]

[build]
exclude-multi-locale = [
    "ach",
    "ia",
    "km",
    "lij",
    "ltg",
    "meh",
    "mix",
    "tl",
]

[env]
    l = "{l10n_base}/{locale}/"


[[paths]]
    reference = "mobile/**"
    l10n = "{l}mobile/**"

[[paths]]
    reference = "mobile/android/**"
    l10n = "{l}mobile/android/**"

[[paths]]
    reference = "mobile/android/base/**"
    l10n = "{l}mobile/android/base/**"
    test = [
        "android-dtd",
    ]

# hand-picked paths from toolkit, keep in sync with jar.mn
[[paths]]
    reference = "dom/chrome/global.dtd"
    l10n = "{l}dom/chrome/global.dtd"

[[paths]]
    reference = "dom/chrome/accessibility/AccessFu.properties"
    l10n = "{l}dom/chrome/accessibility/AccessFu.properties"

[[paths]]
    reference = "dom/chrome/dom/dom.properties"
    l10n = "{l}dom/chrome/dom/dom.properties"

[[paths]]
    reference = "dom/chrome/plugins.properties"
    l10n = "{l}dom/chrome/plugins.properties"

[[paths]]
    reference = "toolkit/chrome/global/aboutAbout.dtd"
    l10n = "{l}toolkit/chrome/global/aboutAbout.dtd"

[[paths]]
    reference = "toolkit/chrome/global/aboutReader.properties"
    l10n = "{l}toolkit/chrome/global/aboutReader.properties"

[[paths]]
    reference = "toolkit/chrome/global/aboutRights.dtd"
    l10n = "{l}toolkit/chrome/global/aboutRights.dtd"

[[paths]]
    reference = "toolkit/chrome/global/charsetMenu.properties"
    l10n = "{l}toolkit/chrome/global/charsetMenu.properties"

[[paths]]
    reference = "toolkit/chrome/global/commonDialogs.properties"
    l10n = "{l}toolkit/chrome/global/commonDialogs.properties"

[[paths]]
    reference = "toolkit/chrome/global/intl.properties"
    l10n = "{l}toolkit/chrome/global/intl.properties"

[[paths]]
    reference = "toolkit/chrome/global/intl.css"
    l10n = "{l}toolkit/chrome/global/intl.css"

[[paths]]
    reference = "toolkit/chrome/search/search.properties"
    l10n = "{l}toolkit/chrome/search/search.properties"

[[paths]]
    reference = "toolkit/chrome/pluginproblem/pluginproblem.dtd"
    l10n = "{l}toolkit/chrome/pluginproblem/pluginproblem.dtd"

[[paths]]
    reference = "toolkit/chrome/global/aboutSupport.dtd"
    l10n = "{l}toolkit/chrome/global/aboutSupport.dtd"

[[paths]]
    reference = "toolkit/chrome/global/aboutSupport.properties"
    l10n = "{l}toolkit/chrome/global/aboutSupport.properties"

[[paths]]
    reference = "toolkit/crashreporter/crashes.dtd"
    l10n = "{l}toolkit/crashreporter/crashes.dtd"

[[paths]]
    reference = "toolkit/crashreporter/crashes.properties"
    l10n = "{l}toolkit/crashreporter/crashes.properties"

[[paths]]
    reference = "toolkit/chrome/global/mozilla.dtd"
    l10n = "{l}toolkit/chrome/global/mozilla.dtd"

[[paths]]
    reference = "toolkit/chrome/global/aboutTelemetry.dtd"
    l10n = "{l}toolkit/chrome/global/aboutTelemetry.dtd"

[[paths]]
    reference = "toolkit/chrome/global/aboutTelemetry.properties"
    l10n = "{l}toolkit/chrome/global/aboutTelemetry.properties"

[[paths]]
    reference = "toolkit/chrome/global/aboutWebrtc.properties"
    l10n = "{l}toolkit/chrome/global/aboutWebrtc.properties"


[[filters]]
    path = [
        "{l}mobile/android/mobile-l10n.js",
        "{l}mobile/android/defines.inc",
    ]
    action = "ignore"

[[filters]]
    path = "{l}mobile/android/defines.inc"
    key = "MOZ_LANGPACK_CONTRIBUTORS"
    action = "ignore"

[[filters]]
    path = "{l}mobile/chrome/region.properties"
    key = [
        "re:^browser\\.search\\.order\\.[1-9]$",
        "re:^browser\\.search\\.[a-zA-Z]+\\.US",
        "re:^browser\\.contentHandlers\\.types\\.[0-5]\\..*$",
        "re:^gecko\\.handlerService\\.schemes\\..+$",
        "re:^gecko\\.handlerService\\.defaultHandlersVersion$",
        "re:^browser\\.suggestedsites\\..+$",
    ]
    action = "ignore"
